### ISSUE TITLE
[1.0.8] battletower resetcooldown <player> only resets properly over a restart

### ISSUE THREAD

**Issue by Rasgnarok** [EnvyWare/EnvyBattleTower#2]
1. Challenge BT
2. Check /battletower, see you have a cooldown
3. `/battletower resetcooldown Rasgnarok`
4. Check /battletower, see you have a cooldown (1h, 54min in my case)
5. Restart server
6. Check /battletower, see your cooldown is gone

**Comment by danorris709** [comment]
Fixed in latest
