### ISSUE TITLE
Battle Tower Kick

### ISSUE THREAD

**Issue by chrisdurocher** [EnvyWare/EnvyBattleTower#3]
Defeating certain NPCs in the Battle Tower has a tendency to kick the challenger, when they should have progressed to face the next NPC.

1. Run /battletower and choose to challenge Battle Tower
2. Defeat NPCs one by one
3. There is a high likelihood, but not 100% chance that defeating the Ground-type NPC(among others that kick less frequently) will cause the challenger to be kicked from Battle Tower. (Challenger should have progressed on to the next NPC.)
4. Challenger will receive win rewards, but be teleported back to spawn.

**Comment by danorris709** [comment]
I think you've reported this to the wrong tracker as you're referring to specific NPCs but this mod does not have any set specific NPCs so I am going to close this issue.
